server:
  port: 8084
spring:
  application:
    name: EHR-SYSTEM
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ehr_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:stan}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}

jwt:
  secret: ${JWT_SECRET:0e7d5a5f9b1c7a8b3e2d6f0c4a9b8e1f5d7c3b9e8f1a0d2c6b4e8f9c1a0b3d5e}
  expiration: ${JWT_EXPIRATION:3600000}